name: CI /CD

on:
push: [main]
pull_requests: [main]

jobs:
test:
runs-on: ubuntu-latest

containers:
image: node:20

steps:
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      node-version: "20"
  - name: Install dependencies
    run: npm ci
  - name: Run tests
    run: npm test
  - name: Build
    run: npm run build
